### ISSUE TITLE
Error Installing Requirements

### ISSUE THREAD

**Issue by jtayl711** [easlice/bandcamp-downloader#19] opened 2023-04-07 12:43 UTC
I'm getting the following error when trying to install requirements.  I tried installing Visual C++ 14 as recommended but that didn't seem to fix anything.

C:\Users\HP User\Downloads\bandcamp-downloader-with-local-browser-cookies3-patch>pip install -r requirements.txt
Collecting beautifulsoup4==4.11.1
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting browser-cookie3==0.14.0
  Using cached browser-cookie3-0.14.0.tar.gz (9.3 kB)
  Preparing metadata (setup.py) ... done
Collecting bs4==0.0.1
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0.tar.gz (484 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HP User\AppData\Local\Temp\pip-install-xkvvw__n\cffi_3b3e6e641f6b4ffb96154407b319b908\setup.py", line 126, in <module>
          if sys.platform == "win32" and uses_msvc():
                                         ^^^^^^^^^^^
        File "C:\Users\HP User\AppData\Local\Temp\pip-install-xkvvw__n\cffi_3b3e6e641f6b4ffb96154407b319b908\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP User\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\config.py", line 224, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\HP User\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\config.py", line 129, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\HP User\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
          self.initialize()
        File "C:\Users\HP User\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP User\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\HP User\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\HP User\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

**Comment by easlice** [comment] 2023-08-22 15:31
Hey @jtayl711, Windows isn't exactly my forte, but I've updated the requirements to a newer versions and I was wondering if you were still seeing this error?

**Comment by easlice** [comment] 2024-03-01 15:25
Hey, I'm closing this issue as I can't reproduce it, but if someone sees this happen again, feel free to open it again and drop any more info here.

**Closed by easlice** 2024-03-01 15:25 UTC
